# fly.toml app configuration file generated for giesing-departures on 2025-12-20T20:47:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'giesing-departures'
primary_region = 'fra'

[env]
  TIMEZONE = 'Europe/Berlin'

[build]
  dockerfile = 'docker/Dockerfile.optimized'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[checks]
  [checks.http]
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 512
